# Blank issues are needded for the link checker action
blank_issues_enabled: true
contact_links:
  - name: SAP BTP Solution Diagram Guidelines - Community Support
    url: https://github.com/SAP/btp-solution-diagrams/discussions
    about: Please ask and answer questions here.
