blank_issues_enabled: false
contact_links:
  - name: SAP BTP Solution Diagram Guidelines - Community Support
    url: https://github.com/SAP/btp-solution-diagrams/discussions
    about: Please ask and answer questions here.
